//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string CS_NO { get; set; }
        public string SHORT_NM { get; set; }
        public string CLAS_NO { get; set; }
        public string FULL_NM { get; set; }
        public string FULL_NM2 { get; set; }
        public string ADDR_IVC { get; set; }
        public string ADDR_IVC2 { get; set; }
        public string ADDR_OFC { get; set; }
        public string ADDR_OFC2 { get; set; }
        public string TO_ADDR { get; set; }
        public string TO_ADDR2 { get; set; }
        public string ADDR_DOC { get; set; }
        public string ADDR_DOC2 { get; set; }
        public string ZNO_IVC { get; set; }
        public string ZNO_OFC { get; set; }
        public string ZNO_TO { get; set; }
        public string ZNO_DOC { get; set; }
        public string PROPRIETOR { get; set; }
        public string CONTACTER { get; set; }
        public string CONTACTER2 { get; set; }
        public string CONTACTER3 { get; set; }
        public string TEL_NO { get; set; }
        public string TEL_NO2 { get; set; }
        public string TEL_NO3 { get; set; }
        public string FAX_NO { get; set; }
        public string E_MAIL { get; set; }
        public string WWW { get; set; }
        public string UNIQUE_NO { get; set; }
        public string TAX_NO { get; set; }
        public string EMP_NO { get; set; }
        public string DEPM_NO { get; set; }
        public string SCHL_NO { get; set; }
        public string CS_TY_NO { get; set; }
        public string SLN_NO { get; set; }
        public string NATION_NO { get; set; }
        public string AREA_NO { get; set; }
        public string PRC_NO { get; set; }
        public string PRC_NO1 { get; set; }
        public string PRC_NO2 { get; set; }
        public string PRC_NO3 { get; set; }
        public Nullable<System.DateTime> OPEN_DT { get; set; }
        public Nullable<System.DateTime> FST_DT { get; set; }
        public Nullable<System.DateTime> LST_DT { get; set; }
        public Nullable<decimal> CAPITAL { get; set; }
        public Nullable<decimal> EMP_TOT { get; set; }
        public string C_SAL { get; set; }
        public string C_CRD { get; set; }
        public string AR_CS_NO { get; set; }
        public string AR_ACT_NO { get; set; }
        public string AR_BCH_NO { get; set; }
        public string NR_ACT_NO { get; set; }
        public string NR_BCH_NO { get; set; }
        public string PR_ACT_NO { get; set; }
        public string PR_BCH_NO { get; set; }
        public string EAR_ACT_NO { get; set; }
        public string EAR_BCH_NO { get; set; }
        public string CURRENCY { get; set; }
        public string TAX_TY { get; set; }
        public Nullable<decimal> TAX_RT { get; set; }
        public string IVC_PAGE { get; set; }
        public string PRC_CDT { get; set; }
        public string PAY_CDT { get; set; }
        public string C_CTL { get; set; }
        public Nullable<decimal> MAX_CRD { get; set; }
        public Nullable<decimal> OVER_RT { get; set; }
        public Nullable<int> AR_DAY { get; set; }
        public Nullable<int> NR_DAY { get; set; }
        public Nullable<int> CASH_DAY { get; set; }
        public string BRAND { get; set; }
        public string DESTINATION { get; set; }
        public string SEA_PORT { get; set; }
        public string SEA_CORP { get; set; }
        public string AIR_PORT { get; set; }
        public string AIR_CORP { get; set; }
        public string SHIP_CORP { get; set; }
        public string AGT_CORP { get; set; }
        public string CLR_CORP { get; set; }
        public string INSP_CORP { get; set; }
        public Nullable<decimal> COMS_RATE { get; set; }
        public Nullable<decimal> INSU_RATE { get; set; }
        public string PRICING_SEQ { get; set; }
        public string C_PRICING { get; set; }
        public Nullable<decimal> DISC_RT { get; set; }
        public string C_VCH { get; set; }
        public string ACC_TY { get; set; }
        public string RCV_TY { get; set; }
        public string NOT_TY { get; set; }
        public string SHIP_TY { get; set; }
        public string BANK { get; set; }
        public string BANK2 { get; set; }
        public string BANK3 { get; set; }
        public string ACC_NO { get; set; }
        public string ACC_NO2 { get; set; }
        public string ACC_NO3 { get; set; }
        public string C_APF { get; set; }
        public string REMK { get; set; }
        public Nullable<System.DateTime> EFF_DT { get; set; }
        public Nullable<System.DateTime> EXP_DT { get; set; }
        public string OWNER_USR_NO { get; set; }
        public string OWNER_GRP_NO { get; set; }
        public Nullable<System.DateTime> ADD_DT { get; set; }
        public string IP_NM { get; set; }
        public string CP_NM { get; set; }
    }
}
