//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EIP01Entities : DbContext
    {
        public EIP01Entities()
            : base("name=EIP01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VIEW_PO_PUBLIC_OBJECT_BOOKING_CAR> VIEW_PO_PUBLIC_OBJECT_BOOKING_CAR { get; set; }
        public virtual DbSet<PDM_CONNECT_COUNT> PDM_CONNECT_COUNT { get; set; }
        public virtual DbSet<IP_Address> IP_Address { get; set; }
        public virtual DbSet<ActionLog> ActionLog { get; set; }
        public virtual DbSet<V_BOOKING_CAR> V_BOOKING_CAR { get; set; }
        public virtual DbSet<V_BOOKING_MEETROOM> V_BOOKING_MEETROOM { get; set; }
        public virtual DbSet<VIEW_PO_PUBLIC_OBJECT_BOOKING_MEETINGROOM> VIEW_PO_PUBLIC_OBJECT_BOOKING_MEETINGROOM { get; set; }
        public virtual DbSet<V_ERP_ITEM> V_ERP_ITEM { get; set; }
        public virtual DbSet<SRVPRODDL> SRVPRODDL { get; set; }
        public virtual DbSet<SRVPRODMT> SRVPRODMT { get; set; }
        public virtual DbSet<V_SRVPRODMT> V_SRVPRODMT { get; set; }
        public virtual DbSet<V_SRVDATAMT> V_SRVDATAMT { get; set; }
        public virtual DbSet<BU_GUESTBOOK> BU_GUESTBOOK { get; set; }
        public virtual DbSet<V_EMP_ALBUM> V_EMP_ALBUM { get; set; }
        public virtual DbSet<PU_ALBUMS> PU_ALBUMS { get; set; }
        public virtual DbSet<PU_CONNECT_COUNT> PU_CONNECT_COUNT { get; set; }
    
        public virtual int DropWorkflowInbox(Nullable<System.Guid> processId)
        {
            var processIdParameter = processId.HasValue ?
                new ObjectParameter("processId", processId) :
                new ObjectParameter("processId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DropWorkflowInbox", processIdParameter);
        }
    
        public virtual int DropWorkflowProcess(Nullable<System.Guid> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DropWorkflowProcess", idParameter);
        }
    
        public virtual int DropWorkflowProcesses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DropWorkflowProcesses");
        }
    
        public virtual int ERP_Mo_ProgressCheck(string iTEM_NO)
        {
            var iTEM_NOParameter = iTEM_NO != null ?
                new ObjectParameter("ITEM_NO", iTEM_NO) :
                new ObjectParameter("ITEM_NO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ERP_Mo_ProgressCheck", iTEM_NOParameter);
        }
    
        public virtual ObjectResult<SearchAllTables_Result> SearchAllTables(string searchStr)
        {
            var searchStrParameter = searchStr != null ?
                new ObjectParameter("SearchStr", searchStr) :
                new ObjectParameter("SearchStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllTables_Result>("SearchAllTables", searchStrParameter);
        }
    
        public virtual int spWorkflowProcessResetRunningStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spWorkflowProcessResetRunningStatus");
        }
    }
}
