//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP_Address
    {
        public int sn { get; set; }
        public string ip_addr { get; set; }
        public string mac_addr { get; set; }
        public string dept { get; set; }
        public string user { get; set; }
        public string device { get; set; }
        public string os { get; set; }
        public string group { get; set; }
        public string antivirus { get; set; }
        public string remark { get; set; }
    }
}
