//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public string ITEM_NO { get; set; }
        public string ITEM_NM { get; set; }
        public string ITEM_SP { get; set; }
        public string ITEM_NM_E { get; set; }
        public string ITEM_SP_E { get; set; }
        public string ITEM_NO_O { get; set; }
        public string C_STA { get; set; }
        public string GRAT_NO { get; set; }
        public string CLAS_NO { get; set; }
        public string CLAS_NO1 { get; set; }
        public string CLAS_NO2 { get; set; }
        public string CLAS_NO3 { get; set; }
        public string CLAS_NO4 { get; set; }
        public string CLAS_NO5 { get; set; }
        public string CLAS_NO6 { get; set; }
        public string CLAS_NO7 { get; set; }
        public string CLAS_NO8 { get; set; }
        public string CLAS_NO9 { get; set; }
        public string CLAS_NO10 { get; set; }
        public string CLAS_NO11 { get; set; }
        public string CLAS_NO12 { get; set; }
        public string ACT_NO { get; set; }
        public string INV_TY { get; set; }
        public string FIN_ITEM_NO { get; set; }
        public string UNIT { get; set; }
        public string UNIT1 { get; set; }
        public string UNIT2 { get; set; }
        public string UNIT3 { get; set; }
        public Nullable<decimal> EXCH_RATE1 { get; set; }
        public Nullable<decimal> EXCH_RATE2 { get; set; }
        public Nullable<decimal> EXCH_RATE3 { get; set; }
        public string C_AU { get; set; }
        public string A_UNIT { get; set; }
        public string W_UNIT { get; set; }
        public string L_UNIT { get; set; }
        public string S_UNIT { get; set; }
        public string V_UNIT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> WEIGHT_DNN { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> LENGTH_DNN { get; set; }
        public Nullable<decimal> AREA { get; set; }
        public Nullable<decimal> AREA_DNN { get; set; }
        public Nullable<decimal> VOLUMN { get; set; }
        public Nullable<decimal> VOLUMN_DNN { get; set; }
        public Nullable<decimal> SAFE_QTY { get; set; }
        public Nullable<decimal> ROR_POT { get; set; }
        public Nullable<decimal> SUP_POT { get; set; }
        public Nullable<decimal> MIN_QTY { get; set; }
        public Nullable<decimal> PCH_QTY { get; set; }
        public Nullable<decimal> ISS_QTY { get; set; }
        public Nullable<decimal> UNIT_QTY { get; set; }
        public Nullable<int> FIX_LT { get; set; }
        public Nullable<int> LEAD_TIME { get; set; }
        public Nullable<int> INSP_LT { get; set; }
        public Nullable<decimal> LOT_QTY { get; set; }
        public string C_LT { get; set; }
        public string WAHO_NO { get; set; }
        public string LOCA_NO { get; set; }
        public string VD_NO { get; set; }
        public string PLINE_NO { get; set; }
        public string EMP_NO { get; set; }
        public string INV_EMP_NO { get; set; }
        public string PUR_EMP_NO { get; set; }
        public string MOC_EMP_NO { get; set; }
        public string TIN_CODE { get; set; }
        public Nullable<int> LLC_BOM { get; set; }
        public Nullable<int> LLC_CST { get; set; }
        public string C_SOURCE { get; set; }
        public string C_BONDED { get; set; }
        public string C_PHANT { get; set; }
        public string C_BCH { get; set; }
        public string C_SR { get; set; }
        public string C_LOCA { get; set; }
        public string C_ROR { get; set; }
        public string C_CYC { get; set; }
        public string C_ISS { get; set; }
        public string C_INSP { get; set; }
        public Nullable<int> VLD_DAY { get; set; }
        public Nullable<int> CHK_DAY { get; set; }
        public string C_ABC { get; set; }
        public Nullable<decimal> MTR_CST { get; set; }
        public Nullable<decimal> LAB_CST { get; set; }
        public Nullable<decimal> OVH_CST { get; set; }
        public Nullable<decimal> SBC_CST { get; set; }
        public Nullable<decimal> LAB_ADD { get; set; }
        public Nullable<decimal> OVH_ADD { get; set; }
        public Nullable<decimal> SBC_ADD { get; set; }
        public Nullable<decimal> MTR_ADD { get; set; }
        public Nullable<decimal> MTR_RT { get; set; }
        public Nullable<decimal> LAB_RT { get; set; }
        public Nullable<decimal> OVH_RT { get; set; }
        public Nullable<decimal> SBC_RT { get; set; }
        public Nullable<decimal> STD_PCHPRC { get; set; }
        public Nullable<decimal> STD_SALPRC { get; set; }
        public Nullable<decimal> STD_SALEXP { get; set; }
        public Nullable<decimal> SAL_PRC { get; set; }
        public string C_TAX { get; set; }
        public string PACK_NO { get; set; }
        public string C_CTL { get; set; }
        public string C_INV { get; set; }
        public string ITEM_DSCP { get; set; }
        public string ITEM_DSCP1 { get; set; }
        public string ITEM_DSCP2 { get; set; }
        public string ITEM_DSCP3 { get; set; }
        public string REMK { get; set; }
        public string IMG_NO { get; set; }
        public string IMG_NO1 { get; set; }
        public string IMG_NO2 { get; set; }
        public string IMG_NO3 { get; set; }
        public string RT_ITEM_NO { get; set; }
        public string RT_NO { get; set; }
        public string DOC_NO { get; set; }
        public string BAR_CODE { get; set; }
        public Nullable<System.DateTime> EFF_DT { get; set; }
        public Nullable<System.DateTime> EXP_DT { get; set; }
        public string C_MPS { get; set; }
        public string C_OUT { get; set; }
        public Nullable<decimal> OUT_RT { get; set; }
        public string C_OVR { get; set; }
        public Nullable<decimal> OVR_RT { get; set; }
        public string QM_NO { get; set; }
        public Nullable<int> PINE_DAY { get; set; }
        public Nullable<int> PURE_DAY { get; set; }
        public string GD_NO { get; set; }
        public string SIZE { get; set; }
        public Nullable<decimal> CTS_RT { get; set; }
        public string PO_TY { get; set; }
        public string MO_TY { get; set; }
        public string C_COST { get; set; }
        public string OWNER_USR_NO { get; set; }
        public string OWNER_GRP_NO { get; set; }
        public Nullable<System.DateTime> ADD_DT { get; set; }
        public string MDY_USR_NO { get; set; }
        public Nullable<System.DateTime> MDY_DT { get; set; }
        public string IP_NM { get; set; }
        public string CP_NM { get; set; }
    }
}
