//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITTIN
    {
        public string DRF_NO { get; set; }
        public string CRD_NO { get; set; }
        public System.DateTime TIN_DT { get; set; }
        public string ITEM_NO { get; set; }
        public string BCH_NO { get; set; }
        public string WAHO_NO { get; set; }
        public string LOCA_NO { get; set; }
        public decimal ACC_QTY { get; set; }
        public decimal TIN_QTY { get; set; }
        public Nullable<decimal> ACC_A_QTY { get; set; }
        public Nullable<decimal> TIN_A_QTY { get; set; }
        public string EMP_NO { get; set; }
        public string C_UPD { get; set; }
        public string VCH_TY { get; set; }
        public string VCH_NO { get; set; }
        public Nullable<int> VCH_SR { get; set; }
        public string C_BCH { get; set; }
        public string C_LOCA { get; set; }
    }
}
