//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRVPRODMT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRVPRODMT()
        {
            this.SRVPRODDL = new HashSet<SRVPRODDL>();
        }
    
        public int id { get; set; }
        public string PROD_NO { get; set; }
        public string PROD_TY { get; set; }
        public string ITEM_NO { get; set; }
        public string M_ITEM_NO { get; set; }
        public string M_ITEM_ID { get; set; }
        public Nullable<System.DateTime> SO_DT { get; set; }
        public string SO_TY { get; set; }
        public string SO_NO { get; set; }
        public Nullable<int> SO_SR { get; set; }
        public string SO_CS_NO { get; set; }
        public string FA_NO { get; set; }
        public string CS_NO { get; set; }
        public string TO_ADDR { get; set; }
        public int PROD_GUAR_MM { get; set; }
        public System.DateTime PROD_GUAR_DT { get; set; }
        public int M_ITEM_GUAR_MM { get; set; }
        public System.DateTime M_ITEM_GUAR_DT { get; set; }
        public string REMK { get; set; }
        public string CO_TY { get; set; }
        public string CO_NO { get; set; }
        public Nullable<int> CO_SR { get; set; }
        public string CS_VCH_NO { get; set; }
        public string QT_TY { get; set; }
        public string QT_NO { get; set; }
        public Nullable<int> QT_SR { get; set; }
        public string OWNER_USR_NO { get; set; }
        public string OWNER_GRP_NO { get; set; }
        public Nullable<System.DateTime> ADD_DT { get; set; }
        public string IP_NM { get; set; }
        public string CP_NM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRVPRODDL> SRVPRODDL { get; set; }
    }
}
