//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRVPRODDL
    {
        public int id { get; set; }
        public string PROD_NO { get; set; }
        public int PROD_SR { get; set; }
        public string ENTRY { get; set; }
        public string DSCP_1 { get; set; }
        public string DSCP_2 { get; set; }
        public string DSCP_3 { get; set; }
        public Nullable<int> MT_id { get; set; }
    
        public virtual SRVPRODMT SRVPRODMT { get; set; }
    }
}
