//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_EMP_ALBUM
    {
        public string EMPLYID { get; set; }
        public string EMPLYNM { get; set; }
        public string DEPID { get; set; }
        public string DEPNM { get; set; }
        public string C_STA { get; set; }
        public Nullable<System.DateTime> REGDT { get; set; }
        public Nullable<System.DateTime> LLFDT { get; set; }
        public string CName { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<System.DateTime> BRTHDT { get; set; }
    }
}
