//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ERP_ITEM
    {
        public string ITEM_NO { get; set; }
        public string ITEM_NM { get; set; }
        public string ITEM_SP { get; set; }
        public string ITEM_NO_O { get; set; }
        public string CLAS_NO { get; set; }
        public string CLAS_NO1 { get; set; }
        public string UNIT { get; set; }
    }
}
