//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SRVDATAMT
    {
        public string VCH_TY { get; set; }
        public string VCH_NO { get; set; }
        public Nullable<System.DateTime> VCH_DT { get; set; }
        public string RCV_MODE { get; set; }
        public string EMP_NO { get; set; }
        public string PROD_NO { get; set; }
        public string CS_NO { get; set; }
        public string PROB_REC { get; set; }
        public string TO_ADDR { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> EXCH_RATE { get; set; }
        public string IVC_PAGE { get; set; }
        public string TAX_TY { get; set; }
        public Nullable<decimal> TAX_RT { get; set; }
        public Nullable<decimal> PART_AMT { get; set; }
        public Nullable<decimal> MMT_AMT { get; set; }
        public Nullable<System.DateTime> PLAN_DT { get; set; }
        public Nullable<System.DateTime> REAL_DT { get; set; }
        public string REMK { get; set; }
        public string C_CLS { get; set; }
        public Nullable<int> N_PRT { get; set; }
        public string C_CFM { get; set; }
        public Nullable<System.DateTime> CFM_DT { get; set; }
        public string OWNER_GRP_NO { get; set; }
        public Nullable<System.DateTime> ADD_DT { get; set; }
        public string CFM_USR_NO { get; set; }
        public string IP_NM { get; set; }
        public string CP_NM { get; set; }
    }
}
