//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vdaddr
    {
        public string VD_NO { get; set; }
        public int SR_NO { get; set; }
        public string ADDR { get; set; }
        public string ADDR2 { get; set; }
        public string ZNO { get; set; }
        public string DEPARTMENT { get; set; }
        public string CONTACTER { get; set; }
        public string TEL_NO { get; set; }
        public string TEL_NO2 { get; set; }
        public string TEL_NO3 { get; set; }
        public string FAX_NO { get; set; }
        public string REMK { get; set; }
    }
}
