//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM3S_EIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR
    {
        public string VD_NO { get; set; }
        public string SHORT_NM { get; set; }
        public string CLAS_NO { get; set; }
        public string UNIQUE_NO { get; set; }
        public string TAX_NO { get; set; }
        public Nullable<System.DateTime> OPEN_DT { get; set; }
        public Nullable<System.DateTime> FST_DT { get; set; }
        public Nullable<System.DateTime> LST_DT { get; set; }
        public Nullable<decimal> CAPITAL { get; set; }
        public Nullable<decimal> EMP_TOT { get; set; }
        public string C_ABC { get; set; }
        public string C_DUE { get; set; }
        public string C_QLY { get; set; }
        public string FULL_NM { get; set; }
        public string FULL_NM2 { get; set; }
        public string ADDR_OFC { get; set; }
        public string ADDR_OFC2 { get; set; }
        public string ADDR_IVC { get; set; }
        public string ADDR_IVC2 { get; set; }
        public string ZNO_OFC { get; set; }
        public string ZNO_IVC { get; set; }
        public string PROPRIETOR { get; set; }
        public string CONTACTER { get; set; }
        public string CONTACTER2 { get; set; }
        public string CONTACTER3 { get; set; }
        public string CURRENCY { get; set; }
        public string PRC_CDT { get; set; }
        public string PAY_CDT { get; set; }
        public string TEL_NO { get; set; }
        public string TEL_NO2 { get; set; }
        public string TEL_NO3 { get; set; }
        public string FAX_NO { get; set; }
        public string E_MAIL { get; set; }
        public string WWW { get; set; }
        public string AP_ACT_NO { get; set; }
        public string AP_BCH_NO { get; set; }
        public string SP_ACT_NO { get; set; }
        public string SP_BCH_NO { get; set; }
        public string NP_ACT_NO { get; set; }
        public string NP_BCH_NO { get; set; }
        public string PP_ACT_NO { get; set; }
        public string PP_BCH_NO { get; set; }
        public string EAP_ACT_NO { get; set; }
        public string EAP_BCH_NO { get; set; }
        public Nullable<int> AP_MM { get; set; }
        public Nullable<int> AP_DD { get; set; }
        public Nullable<int> NP_MM { get; set; }
        public Nullable<int> NP_DD { get; set; }
        public Nullable<int> CASH_MM { get; set; }
        public Nullable<int> CASH_DD { get; set; }
        public string ACC_TY { get; set; }
        public string PAY_TY { get; set; }
        public string IVC_PAGE { get; set; }
        public string TAX_TY { get; set; }
        public Nullable<decimal> TAX_RT { get; set; }
        public string AREA_NO { get; set; }
        public string NATION_NO { get; set; }
        public string BANK { get; set; }
        public string ACC_NO { get; set; }
        public string NOT_TY { get; set; }
        public string C_APF { get; set; }
        public string REMK { get; set; }
        public string EMP_NO { get; set; }
        public Nullable<System.DateTime> EFF_DT { get; set; }
        public Nullable<System.DateTime> EXP_DT { get; set; }
        public string BANK_NO { get; set; }
        public Nullable<decimal> DAP_RT { get; set; }
        public Nullable<decimal> PP_RT { get; set; }
        public string ID_NO { get; set; }
        public string ACC_NM { get; set; }
        public string OVD_NO { get; set; }
    }
}
